In [1]:
import numpy as np
rng = np.random.default_rng(12345)
print(rng)

Generator(PCG64)


In [2]:
rfloat = rng.random()
rfloat

0.22733602246716966

In [3]:
rfloat.is_integer()

False

In [4]:
rfloat.as_integer_ratio()

(255957606517759, 1125899906842624)

In [5]:
rints = rng.integers(low=0, high=10,size=5)

In [6]:
rints

array([7, 3, 2, 7, 6], dtype=int64)

In [14]:
data = np.random.randint(1, 10, 12)
unique_vals = np.unique(data)

In [8]:
unique_vals

array([1, 3, 5, 6, 7, 9])

In [19]:
data

array([2, 4, 6, 8, 1, 6, 2, 6, 6, 6, 4, 7])

In [20]:
unique_vals, indexes = np.unique(data, return_index=True)

In [21]:
indexes

array([ 4,  0,  1,  2, 11,  3], dtype=int64)

<h3 style="text-align:center" > Reversing </h3>

In [22]:
values = np.arange(30, 60, 2)
values

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [23]:
reversed = np.flip(values)

In [24]:
reversed

array([58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30])

In [31]:
reversed.shape

rev = reversed[:,np.newaxis]
rev

array([[58],
       [56],
       [54],
       [52],
       [50],
       [48],
       [46],
       [44],
       [42],
       [40],
       [38],
       [36],
       [34],
       [32],
       [30]])

In [32]:
rT = rev.transpose()

In [33]:
rT

array([[58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30]])

In [35]:
np.flip(rev)

array([[30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48],
       [50],
       [52],
       [54],
       [56],
       [58]])

In [36]:
rev

array([[58],
       [56],
       [54],
       [52],
       [50],
       [48],
       [46],
       [44],
       [42],
       [40],
       [38],
       [36],
       [34],
       [32],
       [30]])

In [37]:
reshaped = rev.reshape((3,-1))

In [38]:
reshaped

array([[58, 56, 54, 52, 50],
       [48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30]])

In [41]:
np.flip(reshaped,axis=0)

array([[38, 36, 34, 32, 30],
       [48, 46, 44, 42, 40],
       [58, 56, 54, 52, 50]])

In [42]:
np.flip(reshaped, axis=1)

array([[50, 52, 54, 56, 58],
       [40, 42, 44, 46, 48],
       [30, 32, 34, 36, 38]])

What was the difference between the ravel and flatten method.

**ravel** returns the view of the parent arr
**flatten** returns the copy of the array