In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [6]:
a

array([0, 1, 2, 3, 4, 5])

In [8]:
b = np.reshape(a, newshape=(6,1), order='C')
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

<h4 style="text-align: center; background-color: white; color: orangered"> How to convert 1D to 2D </h4>

In [9]:
a

array([0, 1, 2, 3, 4, 5])

In [10]:
a.shape

(6,)

In [11]:
a2d = a[:, np.newaxis]

In [12]:
a2d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
a2d.shape

(6, 1)

In [14]:
a3d = a2d[np.newaxis,:,:]
a3d

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5]]])

In [15]:
a3d.shape

(1, 6, 1)

In [16]:
a4d = a3d[..., np.newaxis]
a4d

array([[[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]]]])

In [17]:
a4d.shape

(1, 6, 1, 1)

In [18]:
a5d = a4d[np.newaxis, ...]
a5d

array([[[[[0]],

         [[1]],

         [[2]],

         [[3]],

         [[4]],

         [[5]]]]])

In [19]:
a5d.shape

(1, 1, 6, 1, 1)

In [20]:
a6d =  a5d[..., np.newaxis, :,  :]
a6d

array([[[[[[0]]],


         [[[1]]],


         [[[2]]],


         [[[3]]],


         [[[4]]],


         [[[5]]]]]])

In [21]:
a6d.shape

(1, 1, 6, 1, 1, 1)

In [22]:
a7d =  a6d[..., np.newaxis, :, : , :,  :]

In [23]:
a7d

array([[[[[[[0]]],


          [[[1]]],


          [[[2]]],


          [[[3]]],


          [[[4]]],


          [[[5]]]]]]])

In [24]:
a7d.shape

(1, 1, 1, 6, 1, 1, 1)

In [25]:
b = np.arange(1,50,1)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
c = np.expand_dims(b, axis = (1,2))

In [32]:
c.shape
np.newaxis == None

True

In [33]:
q = b[(b > 5) & (b<20)]

In [34]:
q

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
tensor = np.nonzero(b)

In [37]:
s = np.arange(-10, 10)
s

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [44]:
s = s.reshape(2,5,-1)
print(s)
tensor = np.nonzero(s > -1)
tensor

[[[-10  -9]
  [ -8  -7]
  [ -6  -5]
  [ -4  -3]
  [ -2  -1]]

 [[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]
  [  8   9]]]


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [45]:
coords = tensor
list_oF_coords = list(zip(tensor[0],tensor[1], tensor[2]))

In [46]:
for pair in list_oF_coords:
    print(pair)

(1, 0, 0)
(1, 0, 1)
(1, 1, 0)
(1, 1, 1)
(1, 2, 0)
(1, 2, 1)
(1, 3, 0)
(1, 3, 1)
(1, 4, 0)
(1, 4, 1)


In [49]:
a1 = [[1,1], [2,2]]
a2 = [[3,3], [4,4]]

a3 = np.vstack((a1,a2))
a4 = np.hstack((a1,a2))
a3, a4

(array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]]),
 array([[1, 1, 3, 3],
        [2, 2, 4, 4]]))

hsplit(arr, number)

In [50]:
x = np.arange(1,25).reshape(2,-1)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

As you know, most of numpy operations are on views. So data share the same place between for different variables. Use copy() when you need.