In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

##### Different ways of creating arrays

In [5]:
arr = np.array(((1,2), (3,4), (5,6), (7,8)))
# arrays may also be created by tuples

In [6]:
arr, arr.dtype

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 dtype('int32'))

Numpy block

In [8]:
A = np.ones((2,2))
B = np.eye(2)
C = np.diag((-1,-3))
D = np.zeros((2,2))

In [10]:
np.block([[A,B], [C,D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [-1.,  0.,  0.,  0.],
       [ 0., -3.,  0.,  0.]])

In [16]:
e = np.hstack([A,B])
f = np.vstack([A,B])
g = np.column_stack([C,D])
t = np.row_stack([A,D])
e,f,g,t

(array([[1., 1., 1., 0.],
        [1., 1., 0., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 0.],
        [0., 1.]]),
 array([[-1.,  0.,  0.,  0.],
        [ 0., -3.,  0.,  0.]]),
 array([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]))