In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
def f(x,y):
    return x*12 + y
b = np.fromfunction(f, (5,5), dtype=int)

In [4]:
b

array([[ 0,  1,  2,  3,  4],
       [12, 13, 14, 15, 16],
       [24, 25, 26, 27, 28],
       [36, 37, 38, 39, 40],
       [48, 49, 50, 51, 52]])

In [5]:
b[:,1]

array([ 1, 13, 25, 37, 49])

In [6]:
b[2]

array([24, 25, 26, 27, 28])

For the case below we have two stacked 2D arrays. First one is between(1 to 6) and the remaing one.

In [7]:
c = np.array([
    [[1,2,3],
     [4,5,6]],
    
    [[7,8,9],[10,11,12]]]
    )

In [8]:
c.shape

(2, 2, 3)

In [9]:
c[:,:,2]

array([[ 3,  6],
       [ 9, 12]])

In [10]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


If one wants to iterate over the elements, array can be flattened before processing

In [11]:
for elem in c.flat:
    print(elem)

1
2
3
4
5
6
7
8
9
10
11
12


<h4><b>Resize vs Reshape</b> </h4>

In [12]:
# Resize modifications are modifies the argument, reshape returns a view

a = np.arange(1,25)

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
a.resize((3,2,4))
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [15]:
a.reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [16]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

<i> Cumsum </i>

In [17]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

In [19]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
np.cumsum(c, axis=2)

# Cumulative sum along the given axis
# axis = 0, cumulate along the row axis
# axis = 1 , cumulate along same row

array([[[ 1,  3,  6],
        [ 4,  9, 15]],

       [[ 7, 15, 24],
        [10, 21, 33]]])